# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-12-12 06:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_genericuser_is_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genericuser',
            old_name='company_id',
            new_name='company',
        ),
    ]
