# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-12-17 03:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191212_0637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericuser',
            name='middle_name',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
