version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecretpassword
    ports:
        - "6543:5432"
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000 --settings=bridge.local_settings
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db