# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-01-06 01:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_timestamp', models.DateTimeField(blank=True, null=True)),
                ('updated_timestamp', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_timestamp', models.DateTimeField(blank=True, null=True)),
                ('updated_timestamp', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MeetingComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_timestamp', models.DateTimeField(blank=True, null=True)),
                ('updated_timestamp', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('agenda_item', models.CharField(max_length=255)),
                ('duration', models.DurationField()),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetings.Component')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MeetingStructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_timestamp', models.DateTimeField(blank=True, null=True)),
                ('updated_timestamp', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('meeting_uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('company_id', models.PositiveIntegerField()),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MeetingTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_timestamp', models.DateTimeField(blank=True, null=True)),
                ('updated_timestamp', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('meeting_type', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('company_id', models.PositiveIntegerField()),
                ('public', models.BooleanField(default=False)),
                ('interval', models.CharField(choices=[('day', 'Day'), ('week', 'Week'), ('month', 'Month'), ('year', 'Year')], max_length=5)),
                ('interval_count', models.PositiveSmallIntegerField(default=1)),
                ('template_uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('components', models.ManyToManyField(through='meetings.MeetingComponent', to='meetings.Component')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='meetingstructure',
            name='meeting_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_template', to='meetings.MeetingTemplate'),
        ),
        migrations.AddField(
            model_name='meetingstructure',
            name='participants',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meetingcomponent',
            name='meeting_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetings.MeetingTemplate'),
        ),
        migrations.AddField(
            model_name='cards',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetings.MeetingStructure'),
        ),
    ]
