# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-01-31 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='acitvity_type',
            field=models.CharField(choices=[('brainstormactivity', 'Brainstorm Activity'), ('forcedrankactivity', 'Forced Rank Activity'), ('groupingactivity', 'Grouping Activity'), ('bucketingactivity', 'Bucketing Activity'), ('prioritizationactivity', 'Prioritization Activity')], max_length=100),
        ),
    ]
