# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-03-06 04:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='component',
            old_name='acitvity_type',
            new_name='activity_type',
        ),
    ]
