# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-01-21 15:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='component',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='meetings.MeetingComponent'),
            preserve_default=False,
        ),
    ]
