# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-01-31 20:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meetings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrainstormActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_timestamp', models.DateTimeField(blank=True, null=True)),
                ('updated_timestamp', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetings.Component')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BrainstormCards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_timestamp', models.DateTimeField(blank=True, null=True)),
                ('updated_timestamp', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('brainstorm_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.BrainstormActivity')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BucketedCards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_timestamp', models.DateTimeField(blank=True, null=True)),
                ('updated_timestamp', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('bucketed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BucketingActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_timestamp', models.DateTimeField(blank=True, null=True)),
                ('updated_timestamp', models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_timestamp', models.DateTimeField(blank=True, null=True)),
                ('updated_timestamp', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetings.MeetingStructure')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ForcedRankActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_timestamp', models.DateTimeField(blank=True, null=True)),
                ('updated_timestamp', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetings.Component')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ForcedRankedCards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_timestamp', models.DateTimeField(blank=True, null=True)),
                ('updated_timestamp', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('rank', models.PositiveIntegerField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.Cards')),
                ('prioritization_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.ForcedRankActivity')),
                ('ranked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GroupedCards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_timestamp', models.DateTimeField(blank=True, null=True)),
                ('updated_timestamp', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.Cards')),
                ('grouped_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GroupingActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_timestamp', models.DateTimeField(blank=True, null=True)),
                ('updated_timestamp', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetings.Component')),
                ('grouped_cards', models.ManyToManyField(through='activity.GroupedCards', to='activity.Cards')),
                ('meeting_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetings.MeetingStructure')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PrioritizationActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_timestamp', models.DateTimeField(blank=True, null=True)),
                ('updated_timestamp', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetings.Component')),
                ('meeting_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetings.MeetingStructure')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PrioritizedCards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_timestamp', models.DateTimeField(blank=True, null=True)),
                ('updated_timestamp', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('rank', models.PositiveIntegerField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.Cards')),
                ('prioritization_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.PrioritizationActivity')),
                ('ranked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='prioritizationactivity',
            name='prioritized_cards',
            field=models.ManyToManyField(through='activity.PrioritizedCards', to='activity.Cards'),
        ),
        migrations.AddField(
            model_name='groupedcards',
            name='grouping_activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.GroupingActivity'),
        ),
        migrations.AddField(
            model_name='forcedrankactivity',
            name='force_ranked_cards',
            field=models.ManyToManyField(through='activity.ForcedRankedCards', to='activity.Cards'),
        ),
        migrations.AddField(
            model_name='forcedrankactivity',
            name='meeting_structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetings.MeetingStructure'),
        ),
        migrations.AddField(
            model_name='bucketingactivity',
            name='bucketed_cards',
            field=models.ManyToManyField(through='activity.BucketedCards', to='activity.Cards'),
        ),
        migrations.AddField(
            model_name='bucketingactivity',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetings.Component'),
        ),
        migrations.AddField(
            model_name='bucketingactivity',
            name='meeting_structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetings.MeetingStructure'),
        ),
        migrations.AddField(
            model_name='bucketedcards',
            name='bucketing_activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.BucketingActivity'),
        ),
        migrations.AddField(
            model_name='bucketedcards',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.Cards'),
        ),
        migrations.AddField(
            model_name='brainstormcards',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.Cards'),
        ),
        migrations.AddField(
            model_name='brainstormcards',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='brainstormactivity',
            name='created_cards',
            field=models.ManyToManyField(through='activity.BrainstormCards', to='activity.Cards'),
        ),
        migrations.AddField(
            model_name='brainstormactivity',
            name='meeting_structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetings.MeetingStructure'),
        ),
    ]
