# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-03-24 03:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meetings', '0002_auto_20200306_0436'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_timestamp', models.DateTimeField(blank=True, null=True)),
                ('updated_timestamp', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('activity_uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetings.Component')),
                ('data_input', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='activity.ActivityBase')),
                ('meeting_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetings.MeetingStructure')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BucketedCards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_timestamp', models.DateTimeField(blank=True, null=True)),
                ('updated_timestamp', models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Buckets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_timestamp', models.DateTimeField(blank=True, null=True)),
                ('updated_timestamp', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=25)),
                ('bucketing_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.ActivityBase')),
                ('created_by', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_timestamp', models.DateTimeField(blank=True, null=True)),
                ('updated_timestamp', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('activity_created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.ActivityBase')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetings.MeetingStructure')),
                ('user_created', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ForcedRankedCards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_timestamp', models.DateTimeField(blank=True, null=True)),
                ('updated_timestamp', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('rank', models.PositiveIntegerField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.Cards')),
                ('prioritization_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.ActivityBase')),
                ('ranked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PrioritizedCards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_timestamp', models.DateTimeField(blank=True, null=True)),
                ('updated_timestamp', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('rank', models.PositiveIntegerField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.Cards')),
                ('prioritization_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.ActivityBase')),
                ('ranked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='bucketedcards',
            name='bucket',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='activity.Buckets'),
        ),
        migrations.AddField(
            model_name='bucketedcards',
            name='bucketed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bucketedcards',
            name='bucketing_activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.ActivityBase'),
        ),
        migrations.AddField(
            model_name='bucketedcards',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.Cards'),
        ),
    ]
